### ISSUE TITLE
🫂

### ISSUE THREAD

**Issue by CuriousTommy** [hikari-no-yume/lfjdfljglgjdflgdflgjdfglkjdfgldfjgdlfjkgdfljkgsljgdflgjdflgjdflgkjdflkgjdflkgjdflkgjdflkgjdflkjgdlfk#5]
### Describe the feature or issue.

Seems like you really needed a 🫂

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by CuriousTommy** [comment]
I'll be on my way

**Comment by hikari-no-yume** [comment]
<3
